//LocalHost

###Get 404 not found
GET http://localhost:3000/

###Get all Family Tree
GET http://localhost:3000/relatives

###Get Relative by Id
GET http://localhost:3000/relatives/67df8444e555b98f684d7195

###Create Relative
POST http://localhost:3000/relatives HTTP/1.1
Content-Type: application/json

{
    "firstName":"Daniel Israel",
    "lastName":"Madrid Ontiveros",
    "birthday":"20/03/1997",
    "deathday": null,
    "sex":"male",
    "maritalStatus":"single",
    "fatherName":"",
    "motherName":"Oralia Gonzale Gonzalez",
    "children": null,
    "wifeName": null,
    "lifeDescription": null,
    "facts": null
}


###PUT Relative
PUT http://localhost:3000/relatives/67de04c11e94bcd359860764 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Daniel Israel",
    "lastName":"Madrid Ontiveros",
    "birthday":"20/03/1997",
    "deathday": null,
    "sex":"male",
    "maritalStatus":"single",
    "fatherName":"Jesus Francisco Madrid Rivera",
    "motherName":"Oralia Gonzale Gonzalez",
    "children": null,
    "wifeName": null,
    "lifeDescription": null,
    "facts": null
}

### DELETE Relative
DELETE http://localhost:3000/relatives/67df8444e555b98f684d7195

________________________________________________________________________________

###Get all Temples
GET http://localhost:3000/temples

###Get Temple by Id
GET http://localhost:3000/temples/67df8444e555b98f684d7195

###Create Temple
POST http://localhost:3000/temples HTTP/1.1
Content-Type: application/json

{
    "templeName": "Rome Italy",
    "location": "Rome, Italy",
    "dedicated": "2019, March, 10",
    "area": 41010,
    "imageUrl": "https://content.churchofjesuschrist.org/templesldsorg/bc/Temples/photo-galleries/rome-italy/2019/400x250/1-Rome-Temple-2160936.jpg"}


###PUT Temple
PUT http://localhost:3000/temples/67df8cc637171279725f5d08 HTTP/1.1
Content-Type: application/json

{
    "templeName": "Rome Italy",
    "location": "Rome, Italy",
    "dedicated": "2019, March, 10",
    "area": 41010,
    "imageUrl": "https://content.churchofjesuschrist.org/templesldsorg/bc/Temples/photo-galleries/rome-italy/2019/400x250/1-Rome-Temple-2160936.jpg"}

### DELETE Temple
DELETE http://localhost:3000/temples/67df8444e555b98f684d7195
